config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions'}
  authenticated :user do
    root 'todos#index', as: :authenticated_root
  end
  get 'home/index'
  get 'todos/index'
  get 'home/public_feed'
  post 'todos/update_deleted_column', to: 'todos#update_deleted_column', as: 'update_deleted_column'
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/users/auth/', to: 'users#aws_auth', as: 'aws_auth'
  post '/users/validate_code', to: 'users#validate_code', as: 'validate_code'


  get '/users/:user_id/password_auth/', to: 'users#password_auth', as: 'password_auth'
  post '/users/validate_password_reset_code', to: 'users#validate_password_reset_code', as: 'validate_password_reset_code'

  get 'users/index'
  resources :tasks do
  	collection do
  		put :sort
  	end
  end
  resources :users do
    get :stats
  end
  resources :tags, only: :destroy
  namespace :admin do
    root :to => "dashboard#index"
    resources :dashboard, only: :index
    resources :users do
      member do
        get :make_premium
      end
    end
  end

  resources :thoughts, only: [:new, :update, :destroy]
  
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
	before_action :authenticate_user!
	before_action :validate_admin
  def index
  	@users = User.includes(:tasks).all.order('created_at DESC')
  end


  private 
  def validate_admin
  	if current_user.is_admin == false
  		redirect_to root_path, alert: "You are not permitted to access this Url"
  	end
  end
end

app/views/admin/dashboard/_user.html.erb
<td><%="#{user.first_name} #{user.last_name}" %></td>
<td><%= user.email %></td>
<td class="text-center">
  <div class="profile-tags">
    <span>
      <%= user.tasks.active_tasks.completed_tasks.where.not(title: nil).count %>
      Tasks completed
    </span>
    <span>
      <%= user.streak %> 
      <%= user.streak.to_i > 1 ? 'days' : 'day' %>
      streak
    </span>
  </div>
</td>
<td class="text-premium">
  <% if user.is_premium? %>
    Already Premium
  <% else %>
    <%= link_to 'MAKE PREMIUM', make_premium_admin_user_path(id: user.id), id: "make_premium_#{user.id}", remote: true %>
  <% end %>  
</td>

app/views/admin/dashboard/index.html.erb
<div class="height">
  <div class="row">
    <div class="col-md-8">
      <h3 class="mb-1 mt-5">
        Total Users
        <span class="badge badge-primary"><%= @users.present? ? @users.count : 0 %></span>
      </h3>
    </div>
  </div>
  <table class="table mt-3 admin-users-list table-responsive">
    <thead>
      <tr class="text-center">
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Task / Streak </th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @users.present? &&  @users.each_with_index do |user, index| %>
        <tr class="text-center" id="user_<%= user.id %>">
          <%= render partial: 'user', locals: { user: user } %>          
        </tr>
      <% end %>
    </tbody>
  </table>
</div>