config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions'}
  authenticated :user do
    root 'todos#index', as: :authenticated_root
  end
  get 'home/index'
  get 'todos/index'
  get 'home/public_feed'
  post 'todos/update_deleted_column', to: 'todos#update_deleted_column', as: 'update_deleted_column'
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/users/auth/', to: 'users#aws_auth', as: 'aws_auth'
  post '/users/validate_code', to: 'users#validate_code', as: 'validate_code'


  get '/users/:user_id/password_auth/', to: 'users#password_auth', as: 'password_auth'
  post '/users/validate_password_reset_code', to: 'users#validate_password_reset_code', as: 'validate_password_reset_code'

  get 'users/index'
  resources :tasks do
  	collection do
  		put :sort
  	end
  end
  resources :users do
    get :stats
  end
  resources :tags, only: :destroy
  namespace :admin do
    root :to => "dashboard#index"
    resources :dashboard, only: :index
    resources :users do
      member do
        get :make_premium
      end
    end
  end

  resources :thoughts, only: [:new, :update, :destroy]
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::DashboardController
	before_action :set_user

	def edit
	end

	def update
		if @user.update(user_params)
		else
		end
	end

	def make_premium
		@user.update_attributes(plan_id: User::PREMIUM)
	end

	private
	def set_user
		@user = User.find(params[:id])
	end

	 def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  prepend_before_action :require_no_authentication
  # Render the #edit only if coming from a reset password email link
  append_before_action :assert_reset_token_passed, only: :edit

  # GET /resource/password/new
  def new
    self.resource = resource_class.new
  end

  # POST /resource/password
  def create
    self.resource = User.find_by_email(resource_params[:email])
    yield resource if block_given?

    if resource.present?
      session[:user_id] = resource.id
      client = Aws::CognitoIdentityProvider::Client.new(access_key_id: ENV["AWS_ACCESS_KEY_ID"], secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"])
      begin
        resp = client.forgot_password({
          client_id: ENV["AWS_COGNITO_CLIENT_ID"],
          username: resource_params[:email],
        })
        respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
      rescue => e
        redirect_to new_user_password_path, notice: e.message
      end
    else
      redirect_to new_user_password_path, notice: "Email not found"
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    self.resource = resource_class.new
    set_minimum_password_length
    resource.reset_password_token = params[:reset_password_token]
  end

  # PUT /resource/password
  def update
    user = User.find(params[:user_id])
    self.resource = User.find(params[:user_id])
    resource.password = params[:new_password]
    resource.save(validate: false)
    yield resource if block_given?

    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      if Devise.sign_in_after_reset_password
        flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
        client = Aws::CognitoIdentityProvider::Client.new(access_key_id: ENV["AWS_ACCESS_KEY_ID"], secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"])
        begin
          resp = client.confirm_forgot_password({client_id: ENV["AWS_COGNITO_CLIENT_ID"], username: user.email, confirmation_code: params["verify_code"], password: params["new_password"],})
          set_flash_message!(:notice, flash_message)
          sign_in(resource_name, resource)
        rescue
        end
      else
        set_flash_message!(:notice, :updated_not_active)
      end
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      set_minimum_password_length
      respond_with resource
    end
  end

  protected
    def after_resetting_password_path_for(resource)
      Devise.sign_in_after_reset_password ? after_sign_in_path_for(resource) : new_session_path(resource_name)
    end

    # The path used after sending reset password instructions
    def after_sending_reset_password_instructions_path_for(resource_name)
      user = User.find_by_email(params[:user][:email])
      password_auth_path(user_id: user.id) if is_navigational_format?
    end

    # Check if a reset_password_token is provided in the request
    def assert_reset_token_passed
      if params[:reset_password_token].blank?
        set_flash_message(:alert, :no_token)
        redirect_to new_session_path(resource_name)
      end
    end

    # Check if proper Lockable module methods are present & unlock strategy
    # allows to unlock resource on password reset
    def unlockable?(resource)
      resource.respond_to?(:unlock_access!) &&
        resource.respond_to?(:unlock_strategy_enabled?) &&
        resource.unlock_strategy_enabled?(:email)
    end

    def translation_scope
      'devise.passwords'
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy]
  prepend_before_action :set_minimum_password_length, only: [:new, :edit]
  skip_before_action :verify_authenticity_token, only: :update

  # GET /resource/sign_up
  def new
    build_resource
    yield resource if block_given?
    respond_with resource
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.last_renewed = DateTime.current
    resource.save
    yield resource if block_given?
    if resource.persisted?
      aws_sign_up_resp = resource.add_to_aws_cognito(params[:user][:password])
      if !aws_sign_up_resp.user_confirmed
        session[:aws_auth_user_id] = resource.id
        redirect_to aws_auth_path #(resource.id)
      else
        if resource.active_for_authentication?
          set_flash_message! :notice, :signed_up
          sign_up(resource_name, resource)
          respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    render :edit
  end

  # PUT /resource
  # We need to use a copy of the resource because we don't want to change
  # the current user in place.

  def update_password
    @user = current_user
    if @user.update_with_password(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      redirect_to root_path
    else
      render "edit"
    end
  end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    if params[:user][:password].present?
      if resource.update_with_password(user_params) && resource.aws_update_password(params[:user][:current_password], params[:user][:password])   
        bypass_sign_in(resource)
      else
        flash[:alert] = resource.errors.full_messages
      end 
    else
      resource_updated = update_resource(resource, account_update_params)
      yield resource if block_given?
      if resource_updated
        # if is_flashing_format?
        #   # flash_key = :updated
        # end
        resource.aws_update_firstname_and_last_name(params[:user][:first_name], params[:user][:last_name])
        #set_flash_message :notice, :updated
        bypass_sign_in resource, scope: resource_name
        # respond_with resource, location: after_update_path_for(resource)
      else
        if resource.errors.present? && resource.errors.full_messages.present?
          flash[:alert] = resource.errors.full_messages
        end
        clean_up_passwords resource
        set_minimum_password_length
        # respond_with resource
      end
    end  
  end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message! :notice, :destroyed
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    expire_data_after_sign_in!
    redirect_to new_registration_path(resource_name)
  end

  protected

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
      resource.pending_reconfirmation? &&
      previous != resource.unconfirmed_email
  end

  # By default we want to require a password checks on update.
  # You can overwrite this method in your own RegistrationsController.
  def update_resource(resource, params)
    resource.update(params)
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash = {})
    self.resource = resource_class.new_with_session(hash, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    # resource.add_to_aws_cognito
    after_sign_in_path_for(resource) if is_navigational_format?
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    scope = Devise::Mapping.find_scope!(resource)
    router_name = Devise.mappings[scope].router_name
    context = router_name ? send(router_name) : self
    context.respond_to?(:root_path) ? context.root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    edit_user_registration_path(resource)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", force: true)
    self.resource = send(:"current_#{resource_name}")
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :public_task, :email, :timezone, :password, :password_confirmation, :avatar)
  end

  def user_params
    params[:user].permit(:current_password, :password, :password_confirmation)
  end

  def translation_scope
    'devise.registrations'
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  prepend_before_action :require_no_authentication, only: [:new, :create]
  prepend_before_action :allow_params_authentication!, only: :create
  prepend_before_action :verify_signed_out_user, only: :destroy
  prepend_before_action(only: [:create, :destroy]) { request.env["devise.skip_timeout"] = true }
  # GET /resource/sign_in
  def new
    self.resource = resource_class.new(sign_in_params)
    clean_up_passwords(resource)
    yield resource if block_given?
    respond_with(resource, serialize_options(resource))
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    # begin
    #   aws_sign_in_resp = resource.authenticate_with_aws(params[:user][:password])
    # rescue => e
    #   redirect_to root_path, notice: e.message
    # end
    session[:user_id] = resource.id
    # if (aws_sign_in_resp.authentication_result.access_token.present? && resource.update(access_token: aws_sign_in_resp.authentication_result.access_token))
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    # end
  end

  # DELETE /resource/sign_out
  def destroy
    user = User.find_by(id: session[:user_id])
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    if signed_out
      set_flash_message! :notice, :signed_out
      user.aws_sign_out_resp if user.present?
    end
    yield if block_given?
    respond_to_on_destroy
  end

  protected

  def sign_in_params
    devise_parameter_sanitizer.sanitize(:sign_in)
  end

  def serialize_options(resource)
    methods = resource_class.authentication_keys.dup
    methods = methods.keys if methods.is_a?(Hash)
    methods << :password if resource.respond_to?(:password)
    { methods: methods, only: [:password] }
  end

  def auth_options
    { scope: resource_name, recall: "#{controller_path}#new" }
  end

  def translation_scope
    'devise.sessions'
  end

  private

  # Check if there is no signed in user before doing the sign out.
  #
  # If there is no signed in user, it will set the flash message and redirect
  # to the after_sign_out path.
  def verify_signed_out_user
    if all_signed_out?
      set_flash_message! :notice, :already_signed_out

      respond_to_on_destroy
    end
  end

  def all_signed_out?
    users = Devise.mappings.keys.map { |s| warden.user(scope: s, run_callbacks: false) }

    users.all?(&:blank?)
  end

  def respond_to_on_destroy
    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(*navigational_formats) { redirect_to after_sign_out_path_for(resource_name) }
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def show_avatar(user)
    if user.avatar.present?
      image_tag(user.avatar.url(:thumb).to_s, class: 'avatar-circle')
    else
      render partial: 'shared/avatar', locals: {user: user}
    end
  end
end

app/views/users/_avatar_section.html.erb
<%= show_avatar(resource) %>

app/views/users/_form.html.erb
<%= form_for user, url: user_path(id: user.id), method: :put, remote: true, html: {"data-parsley-validate" => true} do |f| %>
  <% keys = get_date_keys(@grouped_tasks, local_date(user.timezone)) %>
  <div class="row">
    <div class="col-md-2"></div>  
    <div class="col-md-12 col-lg-8">
      <% if user.tasks.active_tasks.present? %>
        <ul class="read-more-wrap list-style-none">
          <% keys.each_with_index do |key, index| %>
            <% tasks_count = @grouped_tasks.select{|c| c[0] == key} %>
            <% tasks_count = tasks_count.present? ? tasks_count.flatten(1).last.count : 0 %>
            <li class="<%=  index > 14 ? 'read-more-target' : '' %>">
              <%= render partial: 'form_parts', locals: {f: f, key: key} %>
            </li>
            <%= f.submit '', style: "display:none;", class: 'hidden', id: 'submit_tag' %>
          <% end %>
        </ul>
      <% else %>
          <%= render partial: 'form_parts', locals: {f: f, key: Time.current.in_time_zone(user.get_timezone).to_date, task: nil} %>
          <%= f.submit '', style: "display:none;", class: 'hidden', id: 'submit_tag' %> 
      <% end %>
      <% if keys.present? && keys.count > 14 %>
        <div class="loader d-none" id="infinite-scrolling" data-page="<%= params[:page].present? ? params[:page].to_i + 1 : 2 %>">Loading...
        </div>
      <% end %>

    </div>  
  </div>
<% end %>

app/views/users/_form_parts.html.erb
<% if false %>
<div id='tasks'>
  <div class="row mt-2">
    <div class="col-10">
      <% day = key.present? ? display_date(key, local_date(f.object.timezone)) : 'Today' %>
      <h4 class="mb-3"><%= key.present? ? (display_date(key, local_date(f.object.timezone))) : "<b>Today</b>".html_safe %></h4>
    </div>
    <div class="col-2 mb-2" id="progress_<%= key %>">
      <%= render partial: 'progress_container', locals: { f: f, key: key, user: nil } %>
    </div>
  
  </div>  
  <div class="row">
    <div class="col-md-12">     
      <div class="<%= f.object.tasks.present? ? 'add-task' : 'd-none' %> pr-4 pl-4 pt-1 pb-0">           
        <ul id="sortable<%= key %>" class="sortable ui-sortable ">
          <% if key == display_date(key, local_date(f.object.timezone)) && f.object.tasks.where(task_date: key).blank? %>
            <p id="no_task_text">No task to show</p>
          <% else %>
            <%= f.fields_for :tasks, f.object.tasks.order("task_date DESC").order(:sort) do |task| %>
              <%= render 'task_fields', :f => task if key == task.object.task_date.to_date %>
            <% end %>
          <% end %>
        </ul>
        <div id='thoughts' class="thoughts_<%= key %>">  
          <ul id="thoughts<%=key%>">
            <%= f.fields_for :thoughts, f.object.thoughts.order("thought_date DESC") do |thought| %>
              <%= render 'thought_fields', :f => thought, :key => key  if key == thought.object.thought_date.to_date %>
            <% end %>     
          </ul>
      </div>
      </div>
    </div>
  </div>
</div>

<!-- <div id='thoughts' class="thoughts_<%= key %>">  
  <div class="row">
    <div class="col-md-12">
      <div class="<%#= f.object.thoughts.present? ? 'add-task' : 'd-none' %> add-thought p-4" >                
        <ul id="thoughts<%#=key%>">
          <%#= f.fields_for :thoughts, f.object.thoughts.order("thought_date DESC") do |thought| %>
            <%#= render 'thought_fields', :f => thought, :key => key  if key == thought.object.thought_date.to_date %>
          <%# end %>     
        </ul>
      </div>
    </div>
  </div>
</div> -->

<div class="row mb-5">
  <div class="col-md-12">
    <% @key = key %>
    <%= link_to_add_association 'Add Task', f, :tasks, :partial => 'new_task_fields', class: 'btn btn-success mt-3', data: {'association-insertion-method' => 'append', 'association-insertion-node' => "#sortable#{@key}" } %>
    <%= link_to_add_association 'Add Thought', f, :thoughts, :partial => 'new_thought_fields', class: "add-thoughts btn btn-outline-dark mt-3 ant_#{key} #{f.object.thoughts.find_by_thought_date(key).present? ? 'd-none': ''}", id: 'add_new_thoughts', 'data-id' => key, data: {'association-insertion-method' => 'append', 'association-insertion-node' => "#thoughts#{@key}" }  %>
    <%= link_to 'Save Thought', 'javascript:void(0);', class: "save-thoughts btn btn-outline-dark mt-3 d-none st_#{key}", id: 'save_thoughts', 'data-id' => key %>
  </div>
</div>

<script type="text/javascript">

  var ready, set_positions;

  set_positions = function(){
    $('.ui-state-default').each(function(i){
      $(this).attr("data-pos",i+1);
    });
  }

  ready = function(){
    
    set_positions();
    $('.sortable').sortable();
    $('.sortable').sortable().bind('sortupdate', function(e, ui) {
      updated_order = []
      set_positions();
      $('.ui-state-default').each(function(i){
        updated_order.push({ id: $(this).data("id"), position: i+1 });
      });

      $.ajax({
        type: "PUT",
        url: '/tasks/sort',
        data: { order: updated_order }
      });
    });
  }

  $(document).ready(ready);
  $(document).on('page:load', ready);
</script>

<% end %>

app/views/users/_new_thought_fields.html.erb
<li class='nested-fields add-thougt-box new-thought-box'>
  <div class="mt-3">
    <div class="form-group">
      <%= f.cktext_area :title, class: 'm-0 thought-area form-control editor new-thought-area', contenteditable: "true" %>
      <%= f.hidden_field :thought_date, value: @key %>
    </div>
    <div class="icon-fa close-thought">
      <%= link_to_remove_association f, :partial => 'new_thought_fields' do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>   
  </div>
</li>

app/views/users/_progress_container.html.erb
<% today_tasks = today_task(f, key, current_user) %>
<% completed_tasks = today_tasks.completed_tasks %>



<div class="progress-loader float-right ml-2" data-animation="1" data-animationStep="5" data-percent="<%= completed_percentage(today_tasks, completed_tasks) %>"></div>

<!-- <div class="progress float-right ml-2" data-percentage="<%= completed_percentage(today_tasks, completed_tasks) %>">
  <span class="progress-left">
    <span class="progress-bar"></span>
  </span>
  <span class="progress-right">
    <span class="progress-bar"></span>
  </span>
  <div class="progress-value">
  </div>
</div> -->
<div class="float-right ml-1">
  <small class="text-muted"><%= completed_status(today_tasks, completed_tasks) %></small>
</div>

app/views/users/_stats_chart_section.html.erb
<%= column_chart @user.tasks.active_tasks.completed_tasks.group_by_day(:task_date, range: @date_from.beginning_of_day..@date_to.end_of_day, format: '"%b %d"').count, colors: ["#5fb760"] %>

app/views/users/_stats_count.html.erb
<% unless range_filter.present? %>
	<div class="task-count">
		<%= @completed_tasks_today %> 
		<span class="count-label">TODAY</span>
	</div>

	<div class="task-count">
		<%= @completed_tasks_week %>  
		<span class="count-label">7 DAYS</span>
	</div>

	<div class="task-count">
		<%= @completed_tasks_month %> 
		<span class="count-label">30 DAYS</span>
	</div>

	<div class="task-count">
		<%= @completed_tasks_total %> 
		<span class="count-label">TOTAL</span>
	</div>
<% else %>
	<div class="task-count">
		<%= @completed_range_tasks %> 
		<span class="count-label">TOTAL FOR RANGE</span>
	</div>

	<div class="task-count">
		<%= @completed_tasks_total %> 
		<span class="count-label">TOTAL</span>
	</div>
<% end %>

app/views/users/_task_fields.html.erb
<% if false %>
<li class="nested-fields ui-state-default ui-sortable-handle add-task-box bb-1" id="task_<%= f.object.id %>" data-id="<%= f.object.id %>" data-pos="<%= f.object.sort %>">
  <div class="checkbox checkbox-success pull-left">
		<%= f.check_box :status, id: "check#{f.object.id}", class: 'styled check-box'  %>
    <label for="check<%= f.object.id %>" class="m-0">
      <%= f.text_area :title, class: 'm-0 title', placeholder: 'Enter a task here...' %>
    </label>
  </div>
  <%= f.hidden_field :task_date, value: f.object.task_date.present? ? f.object.task_date : Time.current.in_time_zone(@user.get_timezone).to_date %>
  <div class="pull-right icon-fa close-task">
    <%= f.hidden_field :_destroy, value: false %>
    <% if @user.tasks.count > 1 %>
      <%= link_to 'javascript:void(null);', :partial => 'task_fields', id: 'delete_button' do %>
        <i class="fa fa-trash"></i>
      <% end %>
    <% end %>
  </div>
</li>
<% end %>

app/views/users/_thought_fields.html.erb
<li class='nested-fields thoughts add-thougt-box' id="thought_<%= f.object.id %>" data-id="<%= f.object.id %>">
  <div class="row">
    <div class="col-md-12 mt-3">
      <div class="form-group">
        <%= hidden_field_tag :thought_id,  '', value: f.object.id, id: "hidden_thought_#{key}" %>
        <%= f.cktext_area :title, class: 'm-0 thought-area form-control editor',id: 'myeditor1', 'data-id': key, contenteditable: "true" %>
       
      </div>
      <%= f.hidden_field :thought_date %>
    </div>
    <div class="pull-right icon-fa close-thought">
        <%= f.hidden_field :_destroy, false %>
        <%= link_to 'javascript:void(null);', :partial => 'thought_fields', id: 'delete_thought_button' do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </div>
  </div>

</li>

app/views/users/new.html.erb
<div id="user_form">
	<%= render partial: 'form', locals: { user: @user} %>
</div>

<div class="alert alert-success undo-alert d-none">
  <i class="fa fa-check text-success"></i> The <span id='to_type'>to-do</span> is in trash <a href="javascript:void(0);" id="undo">Undo</a>
</div>

app/views/users/new.js.erb
$('#user_form').html('<%= escape_javascript(render(:partial => "form", :locals => {user: @user}))%>');

app/views/users/password_auth.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="login mt-5">
      <h1>Please Confirm Your Account</h1>
      <%= form_tag(user_password_path, method: :put) do %>
        <div class="form-group">
          <%= hidden_field_tag 'user_id', @user.id %>
          <%= hidden_field_tag "verify_code",{}, {class: "form-control", id: "verify_code"} %>
          <label for="verify_code" class="font-normal">Please enter verification code sent to your email:</label>
          <input type="text" id="password-pincode-input" class="form-control">
        </div>

        <div class="form-group">
          <label for="new_password">Enter New Password:</label>
          <%= password_field_tag "new_password", nil, {class: "form-control", id: "verify_code"} %>
        </div>
        <div class="form-group text-right">
          <button type="submit" class="btn btn-success btn-custom">Verify</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#password-pincode-input').pincodeInput({
    inputs:6,
    hideDigits: false,
  complete : function(value, e, errorElement){
    $('#verify_code').val(value);
  }
  
});
</script>

app/views/users/stats.html.erb
<div class="container-height p-4 stats-height">
	
<!-- 	<div class="row mt-3 mb-2">
		<div class="col-md-12">
			<h4>Your Stats</h4>
		</div>
	</div> -->

	<div class="row mt-3 mb-2">

        <div class="profile-tags col-lg-4 col-md-7 mt-17">
      		<span class="mr-2 margin-space">
        		<%= @user.tasks.active_tasks.completed_tasks.where.not(title: nil).count %>
        		Tasks completed
      		</span>
      		<span>
        		<%= @user.streak %> 
        		<%= @user.streak.to_i > 1 ? 'days' : 'day' %>
        		streak
      		</span>
    	</div>
		
		<div class="col-lg-4 col-md-5 text-center" id="stats_count">
			<%= render partial: 'stats_count', locals: {range_filter: false} %>
		</div>

		<div class="col-lg-4 col-md-12 mt-16 mb-2">
			<%= form_tag user_stats_path(user_id: @user.id), class: " range-filter mr-1", id: "date_range_form", method: :get, remote: true do %>
				<%= text_field_tag 'daterange',nil, class: "form-control text-center", id: 'datefiler', readonly: true %>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div id="stats_chart">
				<%= render partial: 'stats_chart_section' %>
			</div>
		</div>
	</div>
</div>

app/views/users/update.js.erb
$('#user_form').html('<%= escape_javascript(render(:partial => "form", :locals => {user: @user}))%>');
$('div#thoughts').find('.cke_top').addClass('visibility-hidden')
$('div#thoughts').find('.cke_bottom').addClass('visibility-hidden')
// multiline_support()
// $('#myModal').modal("hide")