config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions'}
  authenticated :user do
    root 'todos#index', as: :authenticated_root
  end
  get 'home/index'
  get 'todos/index'
  get 'home/public_feed'
  post 'todos/update_deleted_column', to: 'todos#update_deleted_column', as: 'update_deleted_column'
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/users/auth/', to: 'users#aws_auth', as: 'aws_auth'
  post '/users/validate_code', to: 'users#validate_code', as: 'validate_code'


  get '/users/:user_id/password_auth/', to: 'users#password_auth', as: 'password_auth'
  post '/users/validate_password_reset_code', to: 'users#validate_password_reset_code', as: 'validate_password_reset_code'

  get 'users/index'
  resources :tasks do
  	collection do
  		put :sort
  	end
  end
  resources :users do
    get :stats
  end
  resources :tags, only: :destroy
  namespace :admin do
    root :to => "dashboard#index"
    resources :dashboard, only: :index
    resources :users do
      member do
        get :make_premium
      end
    end
  end

  resources :thoughts, only: [:new, :update, :destroy]
  
end

app/views/shared/_avatar.html.erb
<span class="avatar-circle">
 	<span class="initials">
  	<%= user.get_initials %>
 	</span>
</span>

app/views/shared/_footer.html.erb
<div class="container pt-4 pb-4">
  <div class="row">
    <div class="col-md-6">
      <a href="#">
        <%= image_tag 'logo.png', alt: '', class: 'logo-footer' %>
      </a>
    </div>
    <div class="col-md-6 text-right pt-2">
        <p class="copy-right mb-0">COPYRIGHT © 2018 ALL RIGHTS RESERVED</p>

    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to current_user.present? ? current_user.is_admin? ? admin_root_path  : authenticated_root_path : root_path do %>
			<%= image_tag 'logo.png', alt: '', class: 'logo-footer logo-header mr-3' %>
		<% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    	<% if current_user.present? %>
      	<li class="nav-item <%= params[:controller] == 'todos' && params[:action] == 'index' ? 'active' : '' %>">
        	<a class="nav-link" href="<%= authenticated_root_path %>">Your tasks <span class="sr-only">(current)</span></a>
      	</li>
      	<li class="nav-item <%= params[:controller] == 'users' && params[:action] == 'stats' ? 'active' : '' %>">
        	<a class="nav-link" href="<%= user_stats_path(current_user.id) %>">Stats</a>
      	</li>
      <%  end %>
			<li class="nav-item <%= params[:controller] == 'home' && params[:action] == 'public_feed' ? 'active' : '' %>">
        <a class="nav-link" href="<%= home_public_feed_path %>">Explore</a>
      </li>      
    </ul>
    <% unless current_user.present? %>
      <div class="form-inline my-2 my-lg-0">
    		<%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary blue-color btn-sm mr-1' %>
  			<%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-success  btn-sm' %>
      </div>
		<% end %>
  </div>
  <% if current_user.present? %>
  	<ul class="navbar-nav mr-auto drop-setting">
  		<%= render partial: 'shared/navbar_menu_main' %>
  	</ul>	
	<% end %>
</nav>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <% if value.class == Array %>
    <div class="<%= flash_class(key) %>"  style="transition: opacity 0.3s linear, top 0.3s ease-out, bottom 0.3s ease-out, margin-top 0.3s ease-out;">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <% value.each do |message| %> 
        <li><%= message %></li>
      <% end %>
    </div>
  <% else %>
    <div class="<%= flash_class(key) %>"  style="transition: opacity 0.3s linear, top 0.3s ease-out, bottom 0.3s ease-out, margin-top 0.3s ease-out;">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <ul>
        <li class="d-inine-block">
          <%= value %>
        </li>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar_menu.html.erb
<div class="task-details space-left">
  <div class="count-number">
    <div class="float-left">
      Task <i class="fa fa-exclamation-circle" data-toggle="tooltip" data-placement="bottom" title="Number of task included in your plan for this billing period"></i>
    </div>
    <div class="float-right">
      <% if current_user.is_free? %>
        <%= current_user.tasks.active_tasks.count %>
        /
        100
      <% else %>
        Unlimited Tasks
      <% end %>  
    </div>
  </div>
</div>
<div class="space-left width-100">
  <div class="progress" style="height: 5px;">
    <div class="progress-bar" role="progressbar" style="width: <%= current_user.tasks.active_tasks.count %>%;" aria-valuenow="<%= current_user.is_free? ? current_user.tasks.active_tasks.count : 2 %>" aria-valuemin="0" aria-valuemax="100"></div>
  </div>
</div>
<% if current_user.is_free? %>
  <div class="space-left pt-2">
    <small>
      Monthly usage resets in
      <% days = distance_of_time_in_words(Date.strptime((current_user.last_renewed.present? ? current_user.last_renewed + 30.days : current_user.created_at).strftime("%m/%d/%Y"), "%m/%d/%Y"), Date.current) %>
      <%= days.eql?("about 1 month") ? "30 days" : days %>
    </small>
  </div>
<% end %>

app/views/shared/_navbar_menu_main.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle btn btn-sm btn-outline-dark profile-image" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  	<%= show_avatar(current_user) %>
  </a>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
  	<div class="space-left">
      <% if current_user.is_free? %>
        <span class="btn btn-secondary btn-disabled btn-sm mr-2">FREE PLAN</span>
        <%= link_to 'Upgrade', edit_user_registration_path(section: 'billing'), class: 'upgrade-btn' %>
      <% else %>
    		<span class="btn btn-secondary btn-disabled btn-sm mr-2">Premium</span>
      <% end %>  
  	</div>
    <div class="dropdown-divider mt-3"></div>
    <div id="navbar_menu">
      
      <%= render partial: 'shared/navbar_menu'%>
    	
    </div>  
  	<div class="dropdown-divider mt-2 mb-0"></div>
  	<%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
  		<i class="fa fa-gear mr-2"></i>Settings
  	<% end %>

  	<%= link_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>
    	<i class="fa fa-power-off mr-2"></i>Log out
    <% end %>
  </div>
</li>