config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => {passwords: 'users/passwords', registrations: 'users/registrations', sessions: 'users/sessions'}
  authenticated :user do
    root 'todos#index', as: :authenticated_root
  end
  get 'home/index'
  get 'todos/index'
  get 'home/public_feed'
  post 'todos/update_deleted_column', to: 'todos#update_deleted_column', as: 'update_deleted_column'
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/users/auth/', to: 'users#aws_auth', as: 'aws_auth'
  post '/users/validate_code', to: 'users#validate_code', as: 'validate_code'


  get '/users/:user_id/password_auth/', to: 'users#password_auth', as: 'password_auth'
  post '/users/validate_password_reset_code', to: 'users#validate_password_reset_code', as: 'validate_password_reset_code'

  get 'users/index'
  resources :tasks do
  	collection do
  		put :sort
  	end
  end
  resources :users do
    get :stats
  end
  resources :tags, only: :destroy
  namespace :admin do
    root :to => "dashboard#index"
    resources :dashboard, only: :index
    resources :users do
      member do
        get :make_premium
      end
    end
  end

  resources :thoughts, only: [:new, :update, :destroy]
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :authenticate_user!, only: [:index, :update]
	# skip_before_action :verify_authenticity_token, only: :update
  
  def index
  	require 'will_paginate/array'
    # current_user.incomplete_tasks if current_user.present?
    @user = current_user.present? ? current_user : User.find(3)
    @user.delete_inactive_todos
    puts "TIMEZONE"*50
    puts Time.now
    puts Time.current
    puts Time.current.in_time_zone(@user.get_timezone)

    @user.tasks.create(task_date: Time.current, status: false) unless @user.tasks.present?
    if params[:date].present?
      @grouped_tasks = @user.tasks.active_tasks.where("Date(task_date) = ?", Date.strptime(params[:date], "%Y-%m-%d").in_time_zone(@user.get_timezone).to_date)
      @grouped_tasks = @grouped_tasks.order("task_date DESC").order(:sort).group_by{|t| t.task_date.in_time_zone(@user.get_timezone).to_date}      
    else
      @grouped_tasks = @user.tasks.active_tasks.where(task_date: Time.current.in_time_zone(@user.get_timezone).to_date)
      @grouped_tasks = @user.tasks.active_tasks.order("task_date DESC").order(:sort).group_by{|t| t.task_date.in_time_zone(@user.get_timezone).to_date}
    # @grouped_tasks = @user.tasks.active_tasks.order("task_date DESC").order(:sort).group_by(&:task_date)
      unless @grouped_tasks.present?
        @grouped_tasks = {Time.current.in_time_zone(@user.get_timezone).to_date => []}.merge!(@grouped_tasks)
      end
    end
    @day_tasks = current_user.tasks.where("Date(task_date) = ? ", Date.strptime(params[:date], "%Y-%m-%d").in_time_zone(@user.get_timezone).to_date) if params[:date].present? 
    @grouped_tasks = @grouped_tasks.to_a.paginate(:page => 1, :per_page => (params[:page].present? ? params[:page].to_i : 1) * 14)
    if params[:date].present?
      render 'index.js'
    end
  end

  def update_deleted_column
    if params["button_type"] == 'task'
      @task = Task.find_by(id: params[:id])
      @task.update(is_deleted: (params["button_action"] == 'make_inactive') ? true : false) if @task.present?
    else
      @thought = Thought.find(params[:id])
      @thought.update(is_deleted: (params["button_action"] == 'make_inactive') ? true : false)
    end
  end

end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_day_todos.html.erb
<div id='tasks'>
  <div class="row mt-2 align-items-center">
    <div class="col-9 mb-2">
      <% day = key.present? ? display_date(key, local_date(current_user.timezone), agent_type(request)) : 'Today' %>
      <h4 class="mb-2"><%= key.present? ? (display_date(key, local_date(current_user.timezone), agent_type(request))) : "<b>Today</b>".html_safe %></h4>
    </div>
    <div class="col-3 text-right">
      <% if index == 0 %>
        <%= link_to root_path(date: "#{key - 1}"), class: 'left-padding icon-style', remote: true do %>
          <i class="fa fa-chevron-left"></i>
        <% end %>
        <%= link_to root_path(date: "#{key + 1}"), class: "icon-style ml-2", remote: true do %>
          <i class="fa fa-chevron-right"></i>
        <% end %>
      <% end %>  

      <% if index == 0 %>
        <input type="text" id="daterangepicker" name="" class="daterange" value="" style="border:none; box-shadow:none; width:0;" readonly="true">
        <label class="icon-style-calendar input-group-addon btn daterange-label icon-style" for="daterange">
           <i class="fa fa-calendar open-datetimepicker"></i>
        </label>
      <% end %>  
      <div class="d-inline-block align-middle" id="progress_<%= key %>">
        <%= render partial: 'progress_container', locals: { f: current_user, key: key, user: nil } %>
      </div>
    </div>
  </div>  
  <div class="row">
    <div class="col-md-12">     
      <div class="<%= current_user.tasks.active_tasks.present? ? 'add-task' : 'd-none' %> pr-4 pl-3 pt-0 pb-0 todos-list">           
        <ul id="sortable<%= key %>" class="sortable ui-sortable">
          <% if key == display_date(key, local_date(current_user.timezone), 'B') && current_user.tasks.active_tasks.where("DATE(task_date = ?)", key).blank? %>
            <p id="no_task_text">No task to show</p>
          <% else %>
            <% current_user.tasks.active_tasks.order("DATE(task_date) DESC").order(:sort).each do |task| %>
              <%= render 'task', :task => task if key == task.task_date.to_date %>
            <% end %>
          <% end %>
        </ul>
        <div id='thoughts' class="thoughts_<%= key %>">  
          <ul id="thoughts<%=key%>" 'data-id'=<%= key %>>
            <% current_user.thoughts.active_thoughts.order("thought_date DESC").each do |thought| %>
              <%= render 'thought', :thought => thought, :key => key  if key == thought.thought_date.to_date %>
            <% end %>     
          </ul>
      </div>
      </div>
    </div>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <% @key = key %>
    <%= link_to 'Add Task', new_task_path(date: key), onclick: "return triggerMe(event, this);", remote: true, class: "btn btn-success mt-3 task_#{key} #{current_user.tasks.active_tasks.count >= current_user.plan.total_tasks ? 'qouta_exceeded' : '' }", id: 'add_task', data: { disable_with: "Please wait...", date: key, id: '' }  %>    
    <%= link_to 'Add Thought', new_thought_path(date: key), remote: true, class: "add-thoughts btn btn-outline-dark mt-3 ant_#{key} #{current_user.thoughts.active_thoughts.find_by_thought_date(key).present? ? 'd-none': ''}", id: 'add_new_thoughts', 'data-id' => key %>
    <%= link_to 'Save Thought', 'javascript:void(0);', class: "save-thoughts btn btn-outline-dark mt-3 d-none st_#{key}", id: 'save_thoughts', 'data-id' => key %>
  </div>
</div>
<div id="rails_tags" data-tags="<%= current_user.tags.present? ? current_user.tags.map(&:title) : [] %>"></div>

<script type="text/javascript">

  var ready, set_positions;

  set_positions = function(){
    $('.ui-state-default').each(function(i){
      $(this).attr("data-pos",i+1);
    });
  }

  ready = function(){
    set_positions();
    $( ".sortable" ).sortable({
      axis: "y",
      cursor: 'move',
      tolerance: "pointer",
      handle: ".handle-sort",
      containment: "parent"
    });

    if ($('#sortable<%= key %>').find('li.add-task-box:visible').length < 1) {
      $('.thoughts_<%= key %>').find('li:visible').addClass('bt-0')
    }
    
    $('.sortable').sortable().bind('sortupdate', function(e, ui) {
      $('.add-task').find('ul.sortable').find('li.add-task-box:first').removeClass('bt-1');
      $('.add-task').find('ul.sortable').find('li.add-task-box:not(:first)').addClass('bt-1');
      $(this).find('.add-task-box').removeAttr('style');
      updated_order = []
      set_positions();
      $('.ui-state-default').each(function(i){
        updated_order.push({ id: $(this).data("id"), position: i+1 });
      });

      $.ajax({
        type: "PUT",
        url: '/tasks/sort',
        data: { order: updated_order }
      });
    });
   
    $('.open-datetimepicker').click(function(event){
      $(this).closest('label').prev().daterangepicker({
        singleDatePicker: true,
        autoApply: true,
        autoUpdateInput: true,
        startDate: moment().format("YYYY-MM-DD"),
        endDate: moment().format("YYYY-MM-DD"),
        locale: {
          "format": "YYYY-MM-DD",
          "separator": "/"
        },
        onSelect: function(dateText, inst) {
        }
      }).on("apply.daterangepicker", function(ev) {
        $.ajax({
          type: "GET",
          url: '/?date='+$(this).val(),
          data: {},
          success: (function(result) {   
          })
        });
      }).focus();
    });
  }

  $(document).ready(ready);
  $(document).on('page:load', ready);
</script>

app/views/todos/_progress_container.html.erb
<% today_tasks = today_task(f, key, current_user) unless today_tasks.present? %>
<% completed_tasks = today_tasks.completed_tasks unless completed_tasks.present? %>

<%= puts "TODAY++++", today_tasks.inspect %>
<%= puts "COMPLETEWD++++", completed_tasks.inspect %>
<div class="progress-loader float-right ml-2" id="progress_loader_<%=key%>" data-animation="1" data-animationStep="5" data-percent="<%= completed_percentage(today_tasks, completed_tasks) %>"></div>

<div class="float-right ml-2 tasks_number">
  <small class="text-muted"><%= completed_status(today_tasks, completed_tasks) %></small>
</div>

app/views/todos/_task.html.erb
<li class="nested-fields ui-state-default add-task-box bt-1" id="task_<%= task.id %>" data-id="<%= task.id %>" data-pos="<%= task.sort %>">
  
    <%= render partial: 'todos/task_detail', locals: {task: task} %>  

</li>

<script type="text/javascript">
  function auto_grow(element) {
    console.log('sdfsd')
    element.style.height = "23px";
    element.style.height = (element.scrollHeight)+"px";
  }
</script>

app/views/todos/_task_detail.html.erb
<div class="task_detail">
	<div class="checkbox checkbox-success pull-left">
		<%= check_box_tag 'status', task.status, task.status, id: "check#{task.id}", class: 'styled check-box'   %>
	  <label for="check<%= task.id %>" class="m-0">
	  </label>
	</div>
	<%= text_area_tag :title, task.title, class: "title tags #{task.title.present? ? 'pointer-cursor' : ''}", placeholder: 'Enter a task here...', readonly: true %>
	<%= hidden_field_tag :task_date, task.task_date.present? ? task.task_date_converted : Time.current.in_time_zone(@user.get_timezone).to_date %>
		<!-- <div class="tag-container" id="tag-container<%= task.id %>">
			<%# if task.tag %>
				<span class="tag-style"><%#= truncate task.tag.try(:title), length: 10, separator: /\w+/ %></span>			
			<%# end %>		
		</div>
		<%# if task.tag %>
			<div class="dropdown" id="tag-dropdown<%#= task.id %>">
				<a class="tag-dropdown delete-tag" href="javascript:void(0);" role="button" data-task-id="<%#= task.id %>" id="<%#= task.tag.id %>"><i class="fa fa-close"></i>
				</a>
			</div>
		<%# end %>	   -->
	<span class="handle-sort pull-right"><i class="fa fa-sort"></i></span>

	<div class="pull-right icon-fa close-task">
	  <%= hidden_field_tag :_destroy, '', value: false %>
	  <%= link_to 'javascript:void(null);', :partial => 'task_fields', id: 'delete_button' do %>
	    <i class="fa fa-trash"></i>
	  <% end %>
	</div>
</div>	

app/views/todos/_thought.html.erb
<li class="nested-fields thoughts add-thougt-box <%= current_user.active_tasks_in_date_count(key) <= 0 ? 'bt-0' : '' %>" id="thought_<%= thought.id %>" data-id="<%= thought.id %>">
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= hidden_field_tag :thought_id, thought.id, id: "hidden_thought_#{key}" %>
        <div class="pos-rel">
          <trix-editor class="m-0 thought-area form-control trix-content editor" id="myeditor_<%=key%>" 'data-id'= <%=key%> contenteditable="true">
            <%= thought.title.present? ? thought.title.html_safe : '' %>
          </trix-editor>
          <!-- <div id="myeditor_<%#=key%>" contenteditable="true" class="m-0 thought-area form-control editor" 'data-id'= <%#=key%>>
            <%#= thought.title.present? ? thought.title.html_safe : '' %>
          </div> -->
        </div>
        
        <%= hidden_field_tag :thought_title, thought.title, id: "thought_title_#{key}", data: { behavior: "trix-editor" } %>
        <%#= text_area_tag "thought_title", thought.title, class: 'm-0 thought-area form-control editor', id: "myeditor_#{key}", 'data-id': key, contenteditable: "true" %>
      </div>
      <%= hidden_field_tag :thought_date, thought.thought_date %>
    </div>
    <div class="pull-right icon-fa close-thought">
        <%= hidden_field_tag :_destroy, false %>
        <%= link_to 'javascript:void(null);', :partial => 'thought_fields', id: 'delete_thought_button' do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </div>
  </div>
</li>

app/views/todos/_todos.html.erb
<% if (params[:date].present? && @grouped_tasks.present?) || (!params[:date].present? && current_user.tasks.active_tasks.present?) %>
  <ul class="read-more-wrap list-style-none">
    <% keys.present? && keys.each_with_index do |key, index| %>
      <% tasks_count = @grouped_tasks.select{|c| c[0] == key} %>
      <% tasks_count = tasks_count.present? ? tasks_count.flatten(1).last.count : 0 %>
      <li class="<%=  index > 14 ? 'read-more-target' : '' %>">
        <%= render partial: 'day_todos', locals: {key: key, index: index} %>
      </li>
    <% end %>
  </ul>
<% else %>
    <ul class="read-more-wrap">
      <li>
      <%= render partial: 'day_todos', locals: {key: params[:date].present? ? Date.strptime(params[:date], "%Y-%m-%d").in_time_zone(@user.get_timezone).to_date : Time.current.in_time_zone(current_user.get_timezone).to_date, task: nil, index: 0} %>
    </li>
    </ul>
<% end %>
<% if keys.present? && keys.count > 14 %>
  <div class="loader d-none" id="infinite-scrolling" data-page="<%= params[:page].present? ? params[:page].to_i + 1 : 2 %>">Loading...
  </div>
<% end %>

app/views/todos/index.html.erb
<% keys = get_date_keys(@grouped_tasks, local_date(current_user.timezone)) %>
<div class="row">
  <div class="col-md-2"></div>  
  <div class="col-md-12 col-lg-8" id="todos_container">
    <%= render partial: 'todos', locals: {keys: keys} %>
  </div>  
</div>


<div class="alert alert-success undo-alert d-none">
  <i class="fa fa-check text-success"></i> The <span id='to_type'>to-do</span> is in trash <a href="javascript:void(0);" id="undo">Undo</a>
</div>


<div class="modal fade show quota_container" id="qouta_exceeded_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="mt-3 mb-4"><b>You've reached your monthly qouta</b></h5>
        <p>You've used all your tasks with your current free plan</p>
        <p>If you wish to continue using Femry we recommend switching to paid plan</p>
        <div class="row">
          <div class="col-md-12">
            <div class="border-free border-free-center p-2 pl-3 pr-3">
              <div class="row">
              <div class="col-md-4">
                <div class="text-success">
                  Free plan
                </div>  
                100 / 100 tasks
              </div>
              <div class="col-md-8 text-right mt-21 mt21-0">
                <% days = distance_of_time_in_words(Date.strptime((current_user.last_renewed.present? ? current_user.last_renewed + 30.days : current_user.created_at).strftime("%m/%d/%Y"), "%m/%d/%Y"), Date.current) %>
                Monthly usage resets in <%= days.eql?("about 1 month") ? "30 days" : days %>
              </div>
            </div>
          </div>
          </div>

        </div>
      </div>
      <div class="modal-footer">
        <%= link_to 'Upgrade my account', edit_user_registration_path(section: 'billing'), class: 'btn btn-large btn-success btn-block' %>
      </div>
    </div>
  </div>
</div>

app/views/todos/index.js.erb
<% keys = params[:date].present? ? @grouped_tasks.map{|c| c[0]} : get_date_keys(@grouped_tasks, local_date(current_user.timezone)) %>

$('#todos_container').html('<%= escape_javascript(render(:partial => "todos", :locals => { keys: keys }))%>');
tags = '<%= current_user.tags.present? ? current_user.tags.map(&:title) : [] %>';
	
	tags = tags.replace(/&quot;/g, '"')	
	$('#rails_tags').attr('data-tags', tags);
<% @day_tasks.present? && @day_tasks.each do |task| %>
	$('li#task_<%= task.id%>').html('<%= escape_javascript(render(:partial => "todos/task_detail", :locals => {key: task.task_date_converted, task: task }))%>');
	var tagAutocompleter = $.MentionsKinder.Autocompleter.Select2Autocompleter.extend({
		select2Options: {
		  tags: JSON.parse(tags)
		}
	});
	initializeAutocompleter('<%= task.id %>', tagAutocompleter);
<% end %>
initialize_progress_loader();

app/views/todos/update_deleted_column.js.erb
<% if @task.present?%>
	<% today_tasks = today_task(nil, @task.task_date_converted, current_user) %>
	<% completed_tasks = today_tasks.completed_tasks %>
	$('#progress_<%= @task.task_date_converted %>').html('<%= escape_javascript(render(:partial => "todos/progress_container", :locals => {f: nil, key: @task.task_date_converted, user: current_user, today_tasks: today_tasks, completed_tasks: completed_tasks  }))%>');
	$('#navbar_menu').html('<%= escape_javascript(render(:partial => "shared/navbar_menu" ))%>');
	$("#progress_loader_<%= @task.task_date_converted %>").empty().removeData().attr('data-percent', '<%= completed_percentage(today_tasks, completed_tasks) %>').circliful({
	    animationStep: 5,
	    foregroundBorderWidth: 70,
	    backgroundBorderWidth: 70,
	    foregroundColor: '#5fb760',
	    backgroundColor: '#ededed',
	    noPercentageSign: true,
	    fontColor: '#fff'
	});

	$('#progress_loader_<%= @task.task_date_converted %>').children("svg").eq(0).children("circle").eq(1).css("stroke-dasharray", '<%= completed_percentage(today_tasks, completed_tasks)*3.6 %>' + ", 20000");
	<% if current_user.tasks.active_tasks.count < current_user.plan.total_tasks %>
	   $('a#add_task').each(function(data, index){
	    $(this).removeClass('qouta_exceeded');
	  });
	<% end %>	
	if ($('li#task_<%= @task.id %>').hasClass('d-none')) {
		new_href = $('li#task_<%= @task.id %>').closest('div#tasks').next().find('a#add_task').attr('href').split("&")[0];
		$('li#task_<%= @task.id %>').closest('div#tasks').next().find('a#add_task').attr('href', new_href);
	}
<% elsif @thought.present? %>
	$(".ant_<%= @thought.thought_date %>").removeClass('d-none');
<% end %>